CREATE TABLE IF NOT EXISTS `project`
(
    `ID`          BIGINT(19) NOT NULL AUTO_INCREMENT,
    `CREATED_AT`  TIMESTAMP,
    `DESCRIPTION` VARCHAR(255),
    `END_DATE`    DATE(10),
    `IDENTIFIER`  VARCHAR(5) UNIQUE,
    `NAME`        VARCHAR(255),
    `START_DATE`  DATE(10),
    `UPDATED_AT`  TIMESTAMP,
    PRIMARY KEY (ID)
);